### PR TITLE
Feature: Collection bullets can be shown in Daily log

### PR DESCRIPTION
**Pull request by aydin41k**
Added a checkbox to the Collections to show that collection's bullets in the Daily log. Bullets in the Daily log, that belong to a Collection, have a little indicator showing which Collection they belong to. I would use it to group my bullets in categories.

### CODE REVIEW

**Comment by jessarcher** [comment]
This is awesome @aydin41k! I'd been thinking of something similar.

I'll check it out over the weekend :smiley:

**Comment by jessarcher** [comment]
Hey!

I've been having a play around with this and need a bit more time to think on it. My original plan for something similar was to do it on a per-bullet basis rather than per-collection. I'm not sure which I like better now :P

There was also a minor issue with the pill overlapping the bullet text for long bullets, so in the `main` branch I've moved the loading indicator so that it's part of the bullet button, which gives us a bit more room to play with on the right. I'm thinking the width of the pill might need to shrink the textarea but not sure yet.

I also went down a rabbit hole of doing something like Twitter mentions where you'd enter a special character (e.g. `@`) and it would pop up a list of all your collections so you could automatically link it. Using something like https://www.tiptap.dev/examples/suggestions.

Anyway, just wanted to let you know I hadn't forgotten this.

**Comment by aydin41k** [comment]
> I'm thinking the width of the pill might need to shrink the textarea but not sure yet.
I did realise that would be an issue. But the pill barely comes in the way, hence I thought it would be "acceptable", tho not "perfect" and didn't worry about it too much. Shrinking the textarea would have a side-effect of a narrow bullet text where the collection name is long (unless you multi-line the collection name as well, but I can't think of a viable way to do it).
How about colour-coding the bullets, instead of showing the collection name? Give each collection a colour and take it from there. But then, I am not sure how strict you are about the current greyscale interface.

> I also went down a rabbit hole of doing something like Twitter mentions where you'd enter a special character (e.g. @)...
IMO that would be excessive. I don't see much of a benefit in or an immediate need for that as a user.

**Comment by jessarcher** [comment]
Thanks again! I'm going to close this one as a similar feature was introduced in #4.

**Pull request closed without merging**
